name: MLOps Workflow
on:
 push:
   branches:
     - main
 pull_request:
   branches:
     - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python3 -m spacy download en_core_web_sm
          python3 -m pip install papermill
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
      - name: Run tests
        run: |
          pytest tests/
      # - name: Train model
      #   run: |
      #     python src/train_model.py
      - name: Save model artifact
        uses: actions/upload-artifact@v2
        with:
          name: trained-model
          path: models/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download model artifact
        uses: actions/download-artifact@v2
        with:
          name: trained-model
          path: models/
      # - name: Deploy model
      #   run: |
      #     python src/deploy_model.py